### ISSUE TITLE
String size failed!

### ISSUE THREAD

**Issue by BlackPedrou** [Nickk888SAMP/TextDraw-Editor#10]
![issue](https://i.imgur.com/222UgHn.png)
I think it would solve it just by increasing the size of the 
```new EditorLString[5000];```

or **NDialog** may be causing the problem

**Comment by Nickk888SAMP** [comment]
Already fixed that in the newest Source Code! Will publish the new FIXED version probably today!

**Comment by Nickk888SAMP** [comment]
Successfully fixed in Version 6.1 [Click to Download](https://github.com/Nickk888SAMP/TextDraw-Editor/releases/tag/6.1)
