### ISSUE TITLE
Capitalization source file vs scriptfiles

### ISSUE THREAD

**Issue by ghost** [Nickk888SAMP/TextDraw-Editor#11]
Was looking over the code (it changed alot since the last time I used it -it became even more awesome, good job!) but I did notice this:
`@stock ExportProject()
...
Line 3344: if(dfile_FileExists("/NTD/Exports"))`
The release however gives you precisely this directory structure:
`scriptfiles/ntd/exports`
(After looking up: All file path defines are OK, just the manual ones aren't)- Guessing those have yet to be changed; Lines: 3117, 3120, 3313, 3319, 3340, 3344, 4550, 4806

Windows doesn't care so much. Linux systems however (tested on Ubuntu Server 20.04)  aren't so happy with it.
Server didn't crash (which I expected) but my client stopped doing anything and reconnected. Project file wasn't created

**Comment by Nickk888SAMP** [comment]
Will look after that issue! Thanks!

**Comment by Nickk888SAMP** [comment]
Successfully fixed in Version 6.1 [Click to Download](https://github.com/Nickk888SAMP/TextDraw-Editor/releases/tag/6.1)
