### ISSUE TITLE
fs fails to load

### ISSUE THREAD

**Issue by Mudok1** [Nickk888SAMP/TextDraw-Editor#12]
ntd.amx load failed 
it only happens to me in 6.1

**Comment by Nickk888SAMP** [comment]
More informations would be great to have... Check if the file "ntd.amx" is inside the filterscripts directory, also check if you are using the streamer plugin! If you are using this script und a linux system, check if the file have the permission to run. Beside the "load failed" message, is there something else written in the server_logs.txt file?
Delete the server_logs.txt file and start the server and the script, after that, post the log here.

**Comment by Mudok1** [comment]
Oh it was the permissions, ty
