### ISSUE TITLE
Menu is not showing!

### ISSUE THREAD

**Issue by Oxynoob** [Nickk888SAMP/TextDraw-Editor#19]
**Why is there no menu is showing? I followed all the instructions, even if I repeat the installation again and again, still no menu showing up. Pls help me! (Sorry for my bad Eng).**

![ntdissue](https://user-images.githubusercontent.com/83830464/117474295-608c7780-af8d-11eb-8426-d2cea91f0f99.png)

**Comment by LinesinRows** [comment]
How to resolve?

**Comment by Oxynoob** [comment]
> How to resolve?

yeah how?

**Comment by LinesinRows** [comment]
My Fixed: NTD_RESOURCES.txd file is not in \models
true way: \models\txd\NTD_RESOURCES.txd

Read How_To_Install.txt

**Comment by Oxynoob** [comment]
**still not working!**

![ntdissue](https://user-images.githubusercontent.com/83830464/118602979-f3c37980-b7e5-11eb-8938-197d56e0b13c.png)

**Comment by Oxynoob** [comment]
> My Fixed: NTD_RESOURCES.txd file is not in \models
> true way: \models\txd\NTD_RESOURCES.txd
> 
> Read How_To_Install.txt

**still not working!**

![ntdissue](https://user-images.githubusercontent.com/83830464/118603075-0fc71b00-b7e6-11eb-8764-9df996449231.png)

**Comment by LinesinRows** [comment]
1. The contents of the "filterscripts" folder must be unpacked into the folder
"filterscripts" in server files.

2. The content of the "scriptfiles" folder should be extracted to the folder
"scriptfiles" in server files.

3. Extract the "NTD_RESOURCES.txd" file into the "models/txd" folder.
which is located in the main game folder.
Path: Grand Theft Auto San Andreas\models\txd

4. The content of the "plugins" folder should be extracted to the "plugins" folder in server files.
Then in "server.cfg" on the "plugins" line, add "sscanf2" ("sscanf2.so" on linux) if you haven't already that is. 
Note: If you are using Linux, you need to download the Linux version of sscanf2!, the
package only contains the Windows version!

5. Open the "server.cfg" file and add "ntd" next to "filterscripts" or use "loadfs ntd"
in the server console, or while in game use "/rcon loadfs ntd" while been logged in as RCON.

If these are don't work for u, try to run in .rar server files.
