### ISSUE TITLE
Not accurate instructions

### ISSUE THREAD

**Issue by Prodocc** [Nickk888SAMP/TextDraw-Editor#29]
When i got these messages:
printf("\n[NTD ERROR] Could not find directory or directories!");
printf("[NTD ERROR] Please create 'NTD' directory inside 'scriptfiles'!");
printf("[NTD ERROR] Within 'NTD' you should create the 'exports', 'projects' and 'languages' directory!");
printf("[NTD ERROR] The script will be unloaded or blocked!\n");

it's says that u need to create 'NTD' directory, in appercase, but actually, but it actually only worked when I changed the folder name to lowercase 'ntd'

**Comment by Nickk888SAMP** [comment]
I'll address this in the 7.0 Version i'm currently working on.
